const projects = [
  {
    id: 1,
    title: "Capstone Project with ESGpedia (Sustainability Intelligence Platform)",
    image: "images/esgpedia.jpg",
    date: "Sep 2025 to May 2026",
    nosocials: "",
    github: "",
    linkedin: "",
    youtube: "",
    website:
      "https://capstoneshowcase.sutd.edu.sg/project/proj-s11-esgpedia-sustainability-intelligence-platform/",
    desc1:
      "Built an ESG data extraction pipeline on Databricks using LLMs (Qwen-VL, Perplexity, OpenAI) to process sustainability reports from SGX-, Bursa Malaysia- and IDX-listed companies at ~97% field completeness and 86.1% extraction accuracy. Engineered a data post-processing layer standardizing extracted ESG metrics into common units and a comparable schema. Shipped a Flask/FastAPI backend with S3 integration, powering an extraction dashboard, anomaly detection on ESG metrics, and an AI chatbot for ESGpedia’s sustainability intelligence platform.",
    desc2: "",
    techstack: [
      "aws",
      "databricks",
      "python",
      "javascript_3d",
      "flask",
      "fastapi",
      "openai",
    ],
  },
  {
    id: 2,
    title: "Natural Language Processing Project (Singlish Chatbot)",
    image: "images/nlpproject.jpg",
    date: "Sep 2025 to Dec 2025",
    nosocials: "",
    github: "https://github.com/yuhueng/NLP-Project",
    linkedin: "",
    youtube: "",
    website: "https://yh-singlish-chatbot.vercel.app",
    desc1:
      "Fine-tuned Qwen3-4B into a Singlish base model using 4-bit QLoRA on a self-constructed dataset, with perplexity of 16.26. Trained 4 persona adapters evaluated via perplexity and human evaluation, deployed via HuggingFace ZeroGPU Spaces. Built a dating chat simulator (React, FastAPI) with LionGuard content moderation, deployed on Vercel and Render.",
    desc2: "",
    techstack: ["python", "javascript_3d", "huggingface", "react", "fastapi"],
  },
  {
    id: 3,
    title: "FabWatcher (Cloud & IoT Project)",
    image: "images/fabwatcher.jpg",
    date: "Sep 2025 to Dec 2025",
    nosocials: "No public links available",
    github: "",
    linkedin: "",
    youtube: "",
    website: "",
    desc1:
      "Designed a 3D printer management system with booking-triggered workflows via AWS EventBridge, Lambda, and MQTT. Implemented real-time print failure detection via YOLO for anomaly classification, streaming telemetry to DynamoDB. Deployed on AWS with a containerized EC2 backend and a static S3 frontend, with a live admin dashboard.",
    desc2: "",
    techstack: ["aws", "dynamodb", "c", "python", "javascript_3d"],
  },
  {
    id: 4,
    title: "RubyOnRails WebApp (DBS DocCheck)",
    image: "images/railsproject.png",
    date: "May 2024 to Aug 2024",
    nosocials: "Due to NDA, unable to show repository",
    github: "",
    linkedin: "",
    youtube: "",
    desc1:
      "Developed a web application using Ruby on Rails, JavaScript, HTML, and CSS to streamline the credit card application process for DBS, targeting foreign users. Implemented robust form validation and user-friendly interfaces to minimize errors and improve the user experience. Collaborated closely with DBS staff to understand requirements and ensure seamless integration with existing systems. Utilized Git for version control, facilitating collaborative development and continuous integration with a team of 6. Deployed the application on Google Cloud, ensuring scalability and reliability. Adopted the Sprint framework, delivering new features every two weeks.",
    desc2: "",
    techstack: [
      "ruby",
      "rails",
      "html_3d",
      "css_3d",
      "javascript_3d",
      "python",
      "mysql",
      "bootstrap_wotext",
      "figma",
      "github",
      "googlecloud",
    ],
  },
  {
    id: 5,
    title: "React WebApp (Personal Portfolio Website)",
    image: "images/personalportfolio.png",
    date: "Jul 2024 - Aug 2024",
    nosocials: "Not Done",
    github: "https://github.com/yuhueng/YH-Web",
    linkedin:
      "https://www.linkedin.com/posts/ngyuhueng_webdevelopment-mernstack-newwebsite-activity-7220129956318564356-emA4?utm_source=share&utm_medium=member_desktop",
    youtube: "",
    desc1:
      "Developed a full-stack personal portfolio website with a focus on creating an aesthetic and user-friendly UI. The front-end was built using JavaScript, HTML, CSS, and React, with styling enhanced by Tailwind CSS. The back-end was implemented using Node.js and Express.js, and the data is managed with a MongoDB database. This project demonstrates my ability to create a visually appealing, responsive, and interactive web application.",
    desc2: "",
    techstack: [
      "javascript_3d",
      "css_3d",
      "html_3d",
      "nodejs",
      "express",
      "react",
      "tailwind_css",
      "mongodb",
    ],
  },
  {
    id: 6,
    title: "Java Application (LeftoverChef)",
    image: "images/leftoverchef.png",
    date: "Jan 2023 - Apr 2024",
    nosocials: "",
    github: "https://github.com/yuhueng/LeftOverChef",
    linkedin:
      "https://www.linkedin.com/posts/ngyuhueng_java-javaprogramming-mobileapp-activity-7186388068256382976-L0yD?utm_source=share&utm_medium=member_desktop",
    youtube: "https://youtu.be/bmkhyujBJh4",
    desc1:
      "Developed a full-stack Android application aimed at reducing food wastage by providing recipe suggestions based on leftover ingredients. The app includes advanced photo analysis capabilities and ingredient recognition using YoloV5 and TensorFlow, integrated with OpenAI and Google Search APIs to generate recipe suggestions. The backend is powered by Firebase, ensuring real-time data storage and retrieval.",
    desc2:
      "Awarded Honorable Mention and a $1,000 prize at the Singtel Information Systems and Programming Merit Award for innovative use of technology in combating food waste.",
    techstack: ["java", "firebase", "openai", "github"],
  },
  {
    id: 7,
    title: "TemasekXSUTD Hackathon (GenAI)",
    image: "images/GenAI2.jpg",
    nosocials: "",
    github: "",
    linkedin:
      "https://www.linkedin.com/posts/ngyuhueng_genaihackathon-temasekxsutd-activity-7175891555591839744-DQPC?utm_source=share&utm_medium=member_desktop",
    youtube: "",
    date: "Mar 2024 - Mar 2024",
    desc1:
      "Collaborated in a team of three to design and develop an AI-powered chatbot during the GenAI Hackathon, hosted by Temasek and SUTD. Partnered with business professionals from Temasek to identify and address daily operational challenges through AI solutions. The chatbot automated responses and assisted in managing workload, significantly improving task handling and productivity for Temasek staff.",
    desc2: "",
    techstack: ["python", "azure"],
  },
];

export default projects;
