const techstackicons = {
    aws: "images/icons/aws.svg",
    bootstrap_wotext: "images/icons/bootstrap_wotext.svg",
    bootstrap: "images/icons/bootstrap.svg",
    c: "images/icons/c.svg",
    cplusplus: "images/icons/c++.svg",
    csharp: "images/icons/csharp.svg",
    css_3d: "images/icons/css_3d.svg",
    figma: "images/icons/figma.svg",
    firebase: "images/icons/firebase.svg",
    github: "images/icons/github.svg",
    googlecloud: "images/icons/googlecloud.svg",
    html_3d: "images/icons/html_3d.svg",
    java: "images/icons/java.svg",
    javascript_3d: "images/icons/javascript_3d.svg",
    javascript: "images/icons/javascript.svg",
    mongodb: "images/icons/mongodb.svg",
    mysql: "images/icons/mysql.svg",
    nodejs: "images/icons/nodejs.svg",
    openai: "images/icons/openai.svg",
    python: "images/icons/python.svg",
    rails: "images/icons/rails.svg",
    react: "images/icons/react.svg",
    ruby: "images/icons/ruby.svg",
    tailwind_css: "images/icons/tailwind-css.svg",
    azure: "images/icons/azure.svg",
    express: "images/icons/express.svg",
  };
  export default techstackicons;
  